export const UPDATE_SIGNUP_USERNAME = 'UPDATE_SIGNUP_USERNAME';
export const UPDATE_SIGNUP_PASSWORD = 'UPDATE_SIGNUP_PASSWORD';
export const UPDATE_LOGIN_USERNAME = 'UPDATE_LOGIN_USERNAME';
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD';
export const UPDATE_SIGNUP_CONFIRM_PASSWORD = 'UPDATE_SIGNUP_CONFIRM_PASSWORD';